Lab Assignment -1
(UCC547)

1.Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [2]:
import numpy as np

arr = np.array([7, 11, 4, 9, 2, 15])

rev_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", rev_arr)


Original Array: [ 7 11  4  9  2 15]
Reversed Array: [15  2  9  4 11  7]


2.Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [3]:
import numpy as np


a = np.array([[5, 8], [2, 6]])
b = np.array([[5, 8], [2, 6]])

result = np.array_equal(a, b)

print("Array A:\n", a)
print("Array B:\n", b)
print("Are both arrays equal?", result)


Array A:
 [[5 8]
 [2 6]]
Array B:
 [[5 8]
 [2 6]]
Are both arrays equal? True


3.Find the most frequent value and their indice(s) in the following arrays:
i.x = np.array([1,2,3,4,5,1,2,1,1,1])
ii.y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
import numpy as np

x = np.array([3, 7, 3, 9, 7, 3, 3, 5, 7])

values, counts = np.unique(x, return_counts=True)
max_count = counts.max()

most_frequent = values[counts == max_count]

print("Array:", x)
print("Most Frequent Value(s):", most_frequent)

for val in most_frequent:
    indices = np.where(x == val)
    print(f"Indices of {val}:", indices[0])


Array: [3 7 3 9 7 3 3 5 7]
Most Frequent Value(s): [3]
Indices of 3: [0 2 5 6]


In [5]:
import numpy as np

y = np.array([4, 6, 4, 8, 6, 4, 9, 6, 6])

values, counts = np.unique(y, return_counts=True)
max_count = counts.max()

most_frequent = values[counts == max_count]

print("Array:", y)
print("Most Frequent Value(s):", most_frequent)

for val in most_frequent:
    indices = np.where(y == val)
    print(f"Indices of {val}:", indices[0])


Array: [4 6 4 8 6 4 9 6 6]
Most Frequent Value(s): [6]
Indices of 6: [1 4 7 8]


4.For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii.
iii.
Sum of all element’s row-wise
Sum of all element’s column-wise

In [6]:
import numpy as np

mat = np.matrix('[7, 2, 5; 1, 9, 3; 4, 6, 8]')

total_sum = mat.sum()
row_sum = mat.sum(axis=1)
column_sum = mat.sum(axis=0)

print("Matrix:\n", mat)
print("Sum of all elements:", total_sum)
print("Row-wise sum:\n", row_sum)
print("Column-wise sum:\n", column_sum)


Matrix:
 [[7 2 5]
 [1 9 3]
 [4 6 8]]
Sum of all elements: 45
Row-wise sum:
 [[14]
 [13]
 [18]]
Column-wise sum:
 [[12 17 16]]
